### ISSUE TITLE
Model criticism: PPC Plots missing section

### ISSUE THREAD

**Issue by aloctavodia** [arviz-devs/Exploratory-Analysis-of-Bayesian-Models#13]

**Comment by OriolAbril** [comment]
Would it be OK to start from https://docs.pymc.io/notebooks/posterior_predictive.html and extend it? Extensions that come to mind:

1. Use ArviZ
1. Prior predictive checks
1. Use `pm.Data`
1. Use hpd plot instead of errorbars?

**Comment by AlexAndorra** [comment]
I agree, that's a good idea!
Depending on when you can start working on that, we can work together, or you / I take the lead -- I should be able to work on that in 2 weeks.
Let me know!
